### ISSUE TITLE
Element swap between untyped vec elements 

### ISSUE THREAD

**Issue by schell** [tower120/any_vec#23]
I'm naively trying to swap elements between two untyped `AnyVec`: 
```rust
    #[test]
    fn anyvec_swap_sanity() {
        let mut a: AnyVec = AnyVec::new::<f32>();
        {
            let mut v = a.downcast_mut::<f32>().unwrap();
            v.push(0.0);
            v.push(1.0);
            v.push(2.0);
        }

        let mut b: AnyVec = AnyVec::new::<f32>();
        {
            let mut v = b.downcast_mut::<f32>().unwrap();
            v.push(10.0);
            v.push(11.0);
            v.push(12.0);
        }

        std::mem::swap(&mut a.at_mut(0), &mut b.at_mut(0));

        assert_eq!(10.0, *a.at(0).downcast_ref::<f32>().unwrap());
    }
``` 
It seems it simply doesn't swap, or the swap is not doing what I expect. Is there a better way to do this?

**Comment by tower120** [comment]
First of all `AnyVec::at` return ElementRef, not T. It internally stores pointer to T and pointer to AnyVec for type-related info:

https://docs.rs/any_vec/0.9.1/any_vec/struct.AnyVec.html#method.at_mut  
https://docs.rs/any_vec/0.9.1/any_vec/element/struct.ElementMut.html  
https://docs.rs/any_vec/0.9.1/any_vec/element/struct.ElementPointer.html  

_Sorry for such "type indiection". That's to unify/simplify implementation._

Second, if you know concrete type you probably can do what you what with [AnyVecTyped::at_mut].
Or, by doing what you do downcast each element to concrete type.

Third. There should be some `Element::as_bytes(&self) -> &[u8]` - I'll add it. With `as_bytes` you could do:
```
std::mem::swap(a.at_mut(0).as_bytes_mut(), b.at_mut.as_bytes_mut());
```

Forth. There "could be" some `Element::swap(&mut self, &mut Element)`.

**Comment by tower120** [comment]
Oh wait you CAN do it now. `ElementPointer` inplements `AnyValue`.  `AnyValue` have https://docs.rs/any_vec/0.9.1/any_vec/any_value/trait.AnyValue.html#tymethod.bytes and https://docs.rs/any_vec/0.9.1/any_vec/any_value/trait.AnyValue.html#tymethod.size - so you do can mem::swap now...

**Comment by schell** [comment]
Thank you! In my use case I don't have the types _at the type level_ to `downcast_mut`, but I do have the `TypeId`. I'll try `as_bytes_mut` and let you know if it works for me :)

**Comment by tower120** [comment]
Wait wait, about `as_bytes_mut` - I meant that I'll DO that. It does not exists yet.

For now, you should manually construct slice from `bytes_mut` + `size` of `AnyValueMut`.
And swap that slices.

**Comment by schell** [comment]
Ah, ok, I did misunderstand, because I just tried `std::mem::swap(&mut (*a.at_mut(0)).bytes_mut(), &mut (*b.at_mut(0)).bytes_mut());` which did not work.

**Comment by tower120** [comment]
You can also add type check for safety:
```
assert_eq!(element_a.value_typeid(), element_b.value_typeid());
```
You don't need to deref manually, you should be able to just `element_b.bytes_mut()`.

**Comment by schell** [comment]
Thank you :) it's all working now. 

I look forward to whatever you decide to add to your API to make this easier, but my use case is solved.

**Comment by tower120** [comment]
Reopen for AnyValue swap implementation tracking.

**Comment by tower120** [comment]
@schell Changes now in main branch. Could you please try that?
`AnyValue::as_bytes()`
`AnyValueMut::as_bytes_mut()`
`AnyValueMut::swap()`
Was added.

**Comment by schell** [comment]
That works and is much nicer. Thank you! 👍

**Comment by tower120** [comment]
Glad to hear that!
May I ask you as a `any_vec` user, what do you think about changing all `downcast_ref<T>() -> Option<T>` into `downcast_ref<T>() -> T` + panic and adding `try_downcast_ref<T>() -> Option<T>`?

Current API follows `Any` API, where all downcasts return `Option<T>`. I personally found that somewhat unergonomic,.. But I'm not sure if diverging API with `std` for sake of ergonomic is worthwhile

**Comment by schell** [comment]
I prefer to keep it in sync with `Any`. I just `unwrap` in the case where I can accept a panic. I don't think it matters all that much either way though.

**Comment by schell** [comment]
Something I would like is the ability to create a typed iterator from `AnyVec` without having to first downcast to `AnyVecTyped`. I'm not sure if that's possible but it would be very convenient!

**Comment by tower120** [comment]
> I prefer to keep it in sync with Any...

Thanks. I was highly unsure about that.

> Something I would like is the ability to create a typed iterator from AnyVec without having to first downcast to AnyVecTyped.

You mean `AnyVec::iter() -> ?` or `AnyVec::iter::<T>() -> T` ?

**Comment by schell** [comment]
More like the latter: `fn downcast_iter<T>(&self) -> Option<std::slice::Iter<'_, T>>` and `fn downcast_iter_mut(&mut self) -> Option<std::slice::IterMut<'_, T>>`.

**Comment by tower120** [comment]
You want instead of
```any_vec.downcast_ref::<T>().unwrap().iter()```
do
```any_vec.downcast_iter::<T>().unwrap()```
?

That is definitely possible... But why?

`AnyVec` and `AnyVecRef`/`AnyVecMut` implement `IntoIterator`. You can just:
```
any_vec.downcast_ref::<T>().unwrap()
```

**Comment by schell** [comment]
Thank you! I worked it out. I have everything I need :)
