### ISSUE TITLE
no_std usage

### ISSUE THREAD

**Issue by ProfFan** [tower120/any_vec#37]
Hello, thank you for this amazing library! I wonder if this lib can be `no_std` so I can use it in embedded/baremetal applications?

Thanks!

**Comment by tower120** [comment]
Good question. I am not an no_std expert, I don't know what exact constraints it have. But looks like, if memory allocation, like std::alloc::* and TypeId works in no_std - it should be possible to make any_vec no_std-friendly. But as far as I'm aware there is no heap/dynamic memory allocator in no_std.

Though, it looks like it is possible to make https://github.com/tower120/any_vec/blob/main/src/mem/stack.rs works in no_std.

If you know how to make this https://github.com/tower120/any_vec/blob/main/src/mem/heap.rs works in no_std - the answer to your question - is "likely yes".

**Comment by tower120** [comment]
Both no_std and no-alloc implemented here https://github.com/tower120/any_vec/tree/no_std .
All lib now no_std. 
For no-alloc disable default "alloc" feature.

Could you please look at it, and tell me what you think?

**Comment by tower120** [comment]
Implemented in v0.14.0
